server:
  port: 8095

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
spring:
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://zipkin-server/
    locator:
      discovery:
        enabled: true
    enabled: true